name: Github Pages Astro CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ru:
    runs-on: ubuntu-22.04
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🐧 Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 🔍 Installation
        run: pnpm install

      - name: 🔧 Build RU — sova.sh
        run: pnpm build
        env:
          DEVTO_API_KEY: '${{ secrets.DEVTO_API_KEY }}'
          YOUTUBE_API_KEY: '${{ secrets.YOUTUBE_API_KEY }}'
          EFFECTOR_COMMUNITY_API_KEY: '${{ secrets.EFFECTOR_COMMUNITY_API_KEY }}'
          SIMPLECAST_API_KEY: '${{ secrets.SIMPLECAST_API_KEY }}'
          PUBLIC_SITE: https://sova.sh
          PUBLIC_LANGUAGE: ru
          PUBLIC_GTAG: UA-67236238-5

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./dist

  en:
    runs-on: ubuntu-22.04
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🐧 Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: 🔍 Installation
        run: pnpm install

      - name: 🔧 Build EN — sergeysova.com
        run: pnpm build
        env:
          DEVTO_API_KEY: '${{ secrets.DEVTO_API_KEY }}'
          YOUTUBE_API_KEY: '${{ secrets.YOUTUBE_API_KEY }}'
          EFFECTOR_COMMUNITY_API_KEY: '${{ secrets.EFFECTOR_COMMUNITY_API_KEY }}'
          SIMPLECAST_API_KEY: '${{ secrets.SIMPLECAST_API_KEY }}'
          PUBLIC_SITE: https://sergeysova.com
          PUBLIC_LANGUAGE: en
          PUBLIC_GTAG: G-PHKCHPT847

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./dist
          repository-name: sergeysova/sergeysova.com
          token: '${{ secrets.ACCESS_TOKEN }}'
